### ISSUE TITLE
请问下像下面这种情况怎么设置配置文件

### ISSUE THREAD

**Issue by dary123** [didi/DroidAssist#13]
((RequestBuilder)Glide.with(v.getContext()).asGif().diskCacheStrategy(DiskCacheStrategy.RESOURCE)).load(uri.getPath()).listener(new RequestListener<GifDrawable>() {
            public boolean onLoadFailed(@Nullable GlideException e, Object model, Target<GifDrawable> target, boolean isFirstResource) {
                return false;
            }

            public boolean onResourceReady(GifDrawable resource, Object model, Target<GifDrawable> target, DataSource dataSource, boolean isFirstResource) {
                return false;
            }
        }).into(holder.img);

我想把jar包里的上述待代码里的asGif().去掉，就这么简单，如何实现

**Comment by wangwang1069** [comment]
你这个写法是错的吧，是应该先 load(url) 再 asGif() 吧

**Comment by wangwang1069** [comment]
如果你的代码类似下面的代码：
Glide.with(this).load("http://xxx/xx.png").asGif().into(imageView);
你想抹掉asGif() 方法的话，你可以这样配置，这样asGif()的方法调用就会失效
    <DroidAssist>
        <Replace>
            <MethodCall>
                <Source extend="false">
                    com.bumptech.glide.GifTypeRequest com.bumptech.glide.DrawableTypeRequest.asGif()
                </Source>
                <Target>
                    $_= $0;
                </Target>
                <Filter >
                    <Exclude>com.bumptech.glide.*</Exclude>
                </Filter>
            </MethodCall>           
        </Replace>
    </DroidAssist>

**Comment by wangwang1069** [comment]
如果你的代码类似下面的代码：
```java
Glide.with(this).load("http://xxx/xx.png").asGif().into(imageView);
```
如果你的意思是要抹掉`asGif()` 方法的调用，你可以使用下面的配置：
```xml
    <DroidAssist>
        <Replace>
            <MethodCall>
                <Source extend="false">
                    com.bumptech.glide.GifTypeRequest com.bumptech.glide.DrawableTypeRequest.asGif()
                </Source>
                <Target>
                    $_= $0;
                </Target>
                <Filter >
                    <Exclude>com.bumptech.glide.*</Exclude>
                </Filter>
            </MethodCall>
        </Replace>
    </DroidAssist>
```
这样 处理后的代码效果等同于：
```java
Glide.with(this).load("http://xxx/xx.png").into(imageView);
```
