### ISSUE TITLE
替换方法调用没有成功

### ISSUE THREAD

**Issue by zjloong** [didi/DroidAssist#14]
配置如下:
```xml
<Replace>
        <MethodCall>
            <Source>
                void com.arialyy.aria.core.download.downloader.Downloader.onPostPre()
            </Source>
            <Target>
                $_= com.arialyy.aria.core.download.downloader.DownloaderFixed.onPostPre();
            </Target>
        </MethodCall>
    </Replace>
```

结果并没有替换成功.

**Comment by safaribest** [comment]
我也是。。demo的 log 也没替换

**Comment by wangwang1069** [comment]
看下有没有设置 Filter 呢，默认情况没有Filter 将不处理，因此将要处理的类 Include 进来
例如：
```xml
<DroidAssist>
    <Global>
        <Filter>
            <Include>*</Include>
        </Filter>
    </Global>

    <Replace>
        <MethodCall>
            <Source>
                int android.util.Log.d(java.lang.String,java.lang.String)
            </Source>
            <Target>
                $_= com.didichuxing.tools.test.LogUtils.log($$);
            </Target>
        </MethodCall>
    </Replace>
</DroidAssist>
```
如果你开了日志的话：可以看到以下日志：
![image](https://user-images.githubusercontent.com/8521940/67541416-77f17000-f71b-11e9-9a83-e4c039341b03.png)
说明替换成功了
在工程的 build/tmp/transformClassesWithDroidAssistForDebug 目录下可以看到处理之后的class

**Comment by wangwang1069** [comment]
补充：如果是方法Call 替换，需要注意该方法是否是被系统 class 调用，如果是直接被系统类调用的(android.jar中的类)，DroidAssist 无法对系统类进行修改，所以此类的方法Call 替换不能成功，除了被android.jar中的类 调用的方法都可以替换，例如 Activity 的 onStart() 方法其实是系统调用的，因此无法在方法调用前后插入代码，但是可以在onStart() 内部插入代码，可以使用 Replace MethodExecution
