### ISSUE TITLE
View.OnclickListener Lambda 表达式

### ISSUE THREAD

**Issue by zjloong** [didi/DroidAssist#21]
/

**Comment by zjloong** [comment]
能不能增加对 lambda 的支持

**Comment by zjloong** [comment]
tv0.setOnClickListener(new OnClickListener() {
            @Instrumented
            public void onClick(View var1) {
                // 使用 DroidAssist 插入的代码
                TraceUtil.traceClick(var1);
                // GrowingIO 插入的代码
                VdsAgent.onClick(this, var1);
                Log.e(">>>", "test0");
            }
        });
        tv1.setOnClickListener((var0) -> {
            // 使用 DroidAssist 插入失败.   GrowingIO插入成功
            VdsAgent.lambdaOnClick(var0);
            Log.e(">>>", "test1");
        });

**Comment by wangwang1069** [comment]
lambda 写法需要调研一下 #

**Comment by zjloong** [comment]
BeforeMethodExecution 只能对 项目源码和第三方库生效吗? 下面的配置没有生效
```xml
<BeforeMethodExecution>
            <Source>void android.view.View.sendAccessibilityEvent(int)</Source>
            <Target>
                {java.lang.System.out.println("sendAccessibilityEvent");}
            </Target>
        </BeforeMethodExecution>
```

**Comment by zjloong** [comment]
> lambda 写法需要调研一下 #

Source 可否模糊匹配, 目前发现 lambda方法会编译为外部类的私有静态方法, 方法名为 
lambda$xxx

**Comment by zjloong** [comment]
/
