### ISSUE TITLE
修改未生效

### ISSUE THREAD

**Issue by cyigo** [didi/DroidAssist#3]
我想修改 Glide库里的GifFrameLoader.getWidth()方法，配置是下面这样的
`<DroidAssist>
	<Global>
        <Filter>
            <Include>*</Include>
        </Filter>
    </Global>
<Insert>
    <BeforeMethodExecution>
        <Source>int com.bumptech.glide.load.resource.gif.GifFrameLoader.getWidth()</Source>
        <Target>System.out.println("BeforeMethodCall");</Target>
    </BeforeMethodExecution>
</Insert>
</DroidAssist>`

在GifFrameLoader.getWidth方法体内，第一行加上代码，反编译出来还是没变，这是为什么，麻烦帮我分析一下

**Comment by wangwang1069** [comment]
经测试时OK的哈，可通过以下步骤排查：
1. 打开日志：设置 logLevel 3
2. 搜索编译日志中是否有：DroidAssist: Insert [method exec] by before: System.out.println("before GifFrameLoader getWidth"); at com.bumptech.glide.load.resource.gif.GifFrameLoader.java:getWidth 编译日志
3. 将编译后的APK反编译确认结果，或者前往目录build/tmp/transformClassesWithDroidAssistForDebug/jar/com.github.bumptech.glide-glide-4.9.0 查看编译的中间结果
4. 可以加入DroidAssist 用户交流QQ群：675637948 获取更多帮助

**Comment by cyigo** [comment]
> 经测试时OK的哈，可通过以下步骤排查：
> 
> 1. 打开日志：设置 logLevel 3
> 2. 搜索编译日志中是否有：DroidAssist: Insert [method exec] by before: System.out.println("before GifFrameLoader getWidth"); at com.bumptech.glide.load.resource.gif.GifFrameLoader.java:getWidth 编译日志
> 3. 将编译后的APK反编译确认结果，或者前往目录build/tmp/transformClassesWithDroidAssistForDebug/jar/com.github.bumptech.glide-glide-4.9.0 查看编译的中间结果
> 4. 可以加入DroidAssist 用户交流QQ群：675637948 获取更多帮助

群号是不是写错了，找不到
