### ISSUE TITLE
build exception:value is not stored in $_

### ISSUE THREAD

**Issue by HDHunter** [didi/DroidAssist#7]
在编译的过程中，碰到一个异常：

`
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sample:transformClassesWithDroidAssistForDebug'.
> com.didichuxing.tools.droidassist.ex.DroidAssistException: Transform failed for class: com.didichuxing.tools.test.MainActivity with error: the resulting value is not stored in $_

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s`

请问这样如果解决？

**Comment by wangwang1069** [comment]
由于疏忽，有一处 Target 配置中返回值未赋值给 $_
在提交：https://github.com/didi/DroidAssist/commit/f2eb58f58f56acfff67b4d4ff2f06c1b91d7ec18 已修复
