### ISSUE TITLE
遗憾的是对于Activity的生命周期不能修改

### ISSUE THREAD

**Issue by XWC95** [didi/DroidAssist#9]
```
 <BeforeMethodCall>
          <Source>void com.didichuxing.tools.test.MainActivity.onCreate(android.os.Binder)</Source>
          <Target>{java.lang.System.out.println("成功");}</Target>
</BeforeMethodCall>
```

**Comment by yuqiang0713** [comment]
> Binder

函数签名配置错了吧 应该是Bundle不是Binder

**Comment by wangwang1069** [comment]
Activity 的 onCreate 的方法的调用是在系统侧调用，APP无法在系统代码里插入相关逻辑，这里可以改用 BeforeMethodExecution 在 onCreate 方法执行时插入逻辑
 <BeforeMethodExecution>
          <Source>void com.didichuxing.tools.test.MainActivity.onCreate(android.os.Binder)</Source>
          <Target>{java.lang.System.out.println("成功");}</Target>
</BeforeMethodExecution>

**Comment by zjloong** [comment]
```xml
<BeforeMethodExecution>
            <Source>void android.view.View.sendAccessibilityEvent(int)</Source>
            <Target>
                {java.lang.System.out.println("sendAccessibilityEvent");}
            </Target>
        </BeforeMethodExecution>
```
使用 BeforeMethodExecution 在方法执行时插入逻辑失败
